[project]
name = "omaamp"
version = "1.0.0"
description = "A classic Winamp-style modular MP3 & audio player with themes, 10-band EQ, spectrum analyzer, and playlist manager."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "PyQt6>=6.6.0",
    "pygame>=2.5.0",
    "mutagen>=1.47.0",
    "numpy>=1.26.0",
    "miniaudio>=1.71",
    "soundfile>=0.14.0",
    "scipy>=1.15.3",
    "sounddevice>=0.5.6",
]

[project.scripts]
omaamp = "main:main"
